<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBjxrdko\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBjxrdko/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBjxrdko.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBjxrdko\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBjxrdko\appProdProjectContainer([
    'container.build_hash' => 'Bjxrdko',
    'container.build_id' => 'fc325011',
    'container.build_time' => 1602938526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBjxrdko');
